name: Generate Documentation

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  literate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      # Step 2: Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      # Step 3: Cache Julia packages
      - name: Cache Julia packages
        uses: julia-actions/cache@v1

      # Step 4: Install dependencies
      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      # Step 5: Install Literate explicitly
      - name: Install Literate explicitly
        run: julia --project=. -e 'import Pkg; Pkg.add("Literate")'

      # Step 6: Ensure docs/md directory exists
      - name: Ensure docs/md directory exists
        run: mkdir -p docs/md

      # Step 7: Run Literate.jl
      - name: Run Literate.jl
        run: julia --project=. -e 'using Literate; Literate.markdown("scripts/Literate.jl", "docs/md", documenter=false)'

      # Step 8: Debug generated files
      - name: Debug generated files
        run: ls -R docs/md

      # Step 9: Commit and push documentation
      - name: Commit and push documentation
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/md/*
          git commit -m "Generate Markdown documentation from Literate.jl" || echo "No changes to commit"
          git push
